server:
  error.whitelabel.enabled: false
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
        order_inserts: true
      javax:
        persistence:
          query.timeout: 10000
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dota
    username: sa
    password: password
  banner:
    image:
      location: classpath:banner.png
      width: 200
      height: 100
      margin: 1
  h2:
    console:
      enabled: true

logging.config: classpath:logback-${ENV:development}.xml
patterns:
  hero:
    damage: ^\[(.*)\].*npc_dota_hero_(.*)\s.*hits.*npc_dota_hero_(.*).*\swith\s(.*)\sfor\s(\d*)\sdamage.*$
    spell: ^\[(.*)\].*npc_dota_hero_(.*)\scasts\sability\s*(.*)\s*\(.*$
    kill: ^\[(.*)\].*npc_dota_hero_(.*)\sis\skilled.*npc_dota_hero_(.*)$
    item: ^\[(.*)\].*npc_dota_hero_(.*)\sbuys\sitem\s*item_(.*)$
    trash: ^(.*)$